version: '3'
services:
  redis:
    image: "redis:alpine"
    container_name: redis-cache
    ports:
     - "6379:6379"
    expose:
      - 6379
  db:
    image: mysql:5.7
    container_name: prods_db
    restart: always
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '{MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - prods_db:/var/lib/mysql
volumes:
  prods_db: 